version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "install step"
  pre_build:
    commands:
      - ls
  build:
    commands:
      - zip -r test.zip .
      - aws --version
      - pwd
  post_build:
    commands:
      - echo Post build step
      - ls